const product = [
  {
    id: 1,
    name: "Women Dress",
    desc: "Stylish casual women dress",
    price: 499,
    rating: 4.2,
    review: 120,
    category: "female",
    img: "https://picsum.photos/300/300?random=1",
  },
  {
    id: 2,
    name: "Women Top",
    desc: "Comfortable cotton top",
    price: 399,
    rating: 4.0,
    review: 95,
    category: "female",
    img: "https://picsum.photos/300/300?random=2",
  },
  {
    id: 3,
    name: "Women Jeans",
    desc: "Blue slim fit jeans",
    price: 799,
    rating: 4.4,
    review: 210,
    category: "female",
    img: "https://picsum.photos/300/300?random=3",
  },
  {
    id: 4,
    name: "Women Kurti",
    desc: "Traditional printed kurti",
    price: 699,
    rating: 4.3,
    review: 130,
    category: "female",
    img: "https://picsum.photos/300/300?random=4",
  },
  {
    id: 5,
    name: "Women Saree",
    desc: "Elegant designer saree",
    price: 1499,
    rating: 4.6,
    review: 340,
    category: "female",
    img: "https://picsum.photos/300/300?random=5",
  },

  {
    id: 6,
    name: "Men Shirt",
    desc: "Formal white shirt",
    price: 699,
    rating: 4.1,
    review: 180,
    category: "men",
    img: "https://picsum.photos/300/300?random=6",
  },
  {
    id: 7,
    name: "Men T-Shirt",
    desc: "Round neck casual t-shirt",
    price: 349,
    rating: 4.3,
    review: 145,
    category: "men",
    img: "https://picsum.photos/300/300?random=7",
  },
  {
    id: 8,
    name: "Men Jeans",
    desc: "Regular fit denim jeans",
    price: 899,
    rating: 4.5,
    review: 260,
    category: "men",
    img: "https://picsum.photos/300/300?random=8",
  },
  {
    id: 9,
    name: "Men Jacket",
    desc: "Winter leather jacket",
    price: 1999,
    rating: 4.7,
    review: 420,
    category: "men",
    img: "https://picsum.photos/300/300?random=9",
  },
  {
    id: 10,
    name: "Men Hoodie",
    desc: "Warm cotton hoodie",
    price: 999,
    rating: 4.4,
    review: 175,
    category: "men",
    img: "https://picsum.photos/300/300?random=10",
  },

  {
    id: 11,
    name: "Running Shoes",
    desc: "Lightweight sports shoes",
    price: 1299,
    rating: 4.6,
    review: 310,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=11",
  },
  {
    id: 12,
    name: "Sneakers",
    desc: "Trendy casual sneakers",
    price: 1499,
    rating: 4.4,
    review: 200,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=12",
  },
  {
    id: 13,
    name: "Sandals",
    desc: "Comfortable daily wear sandals",
    price: 599,
    rating: 4.0,
    review: 90,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=13",
  },
  {
    id: 14,
    name: "Loafers",
    desc: "Premium leather loafers",
    price: 1799,
    rating: 4.5,
    review: 150,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=14",
  },
  {
    id: 15,
    name: "Sports Shoes",
    desc: "Gym and running shoes",
    price: 1599,
    rating: 4.7,
    review: 280,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=15",
  },

  {
    id: 16,
    name: "Women Top",
    desc: "Stylish printed top",
    price: 450,
    rating: 4.1,
    review: 110,
    category: "female",
    img: "https://picsum.photos/300/300?random=16",
  },
  {
    id: 17,
    name: "Women Skirt",
    desc: "Fashionable long skirt",
    price: 650,
    rating: 4.2,
    review: 87,
    category: "female",
    img: "https://picsum.photos/300/300?random=17",
  },
  {
    id: 18,
    name: "Women Suit",
    desc: "Designer ethnic suit",
    price: 1399,
    rating: 4.5,
    review: 201,
    category: "female",
    img: "https://picsum.photos/300/300?random=18",
  },
  {
    id: 19,
    name: "Women Gown",
    desc: "Party wear gown",
    price: 1899,
    rating: 4.8,
    review: 300,
    category: "female",
    img: "https://picsum.photos/300/300?random=19",
  },
  {
    id: 20,
    name: "Women Blazer",
    desc: "Office wear blazer",
    price: 1299,
    rating: 4.3,
    review: 90,
    category: "female",
    img: "https://picsum.photos/300/300?random=20",
  },

  {
    id: 21,
    name: "Men Polo",
    desc: "Premium polo t-shirt",
    price: 799,
    rating: 4.4,
    review: 210,
    category: "men",
    img: "https://picsum.photos/300/300?random=21",
  },
  {
    id: 22,
    name: "Men Trouser",
    desc: "Formal office trouser",
    price: 899,
    rating: 4.2,
    review: 122,
    category: "men",
    img: "https://picsum.photos/300/300?random=22",
  },
  {
    id: 23,
    name: "Men Blazer",
    desc: "Wedding blazer",
    price: 2499,
    rating: 4.8,
    review: 310,
    category: "men",
    img: "https://picsum.photos/300/300?random=23",
  },
  {
    id: 24,
    name: "Men Kurta",
    desc: "Traditional kurta",
    price: 999,
    rating: 4.5,
    review: 180,
    category: "men",
    img: "https://picsum.photos/300/300?random=24",
  },
  {
    id: 25,
    name: "Men Shorts",
    desc: "Casual summer shorts",
    price: 499,
    rating: 4.0,
    review: 75,
    category: "men",
    img: "https://picsum.photos/300/300?random=25",
  },

  {
    id: 26,
    name: "Boots",
    desc: "Leather ankle boots",
    price: 2299,
    rating: 4.6,
    review: 230,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=26",
  },
  {
    id: 27,
    name: "Flip Flops",
    desc: "Comfortable slippers",
    price: 299,
    rating: 3.9,
    review: 80,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=27",
  },
  {
    id: 28,
    name: "Canvas Shoes",
    desc: "Everyday casual shoes",
    price: 899,
    rating: 4.2,
    review: 140,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=28",
  },
  {
    id: 29,
    name: "Formal Shoes",
    desc: "Premium office shoes",
    price: 1899,
    rating: 4.5,
    review: 195,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=29",
  },
  {
    id: 30,
    name: "Training Shoes",
    desc: "Multi-purpose gym shoes",
    price: 1699,
    rating: 4.7,
    review: 290,
    category: "footwear",
    img: "https://picsum.photos/300/300?random=30",
  },
];

module.exports = product;